version: ~> 1.0

import: scala/scala-dev:travis/default.yml

language: scala
scala:
  - 2.13.1

jobs:
  include:
    - stage: check
      name: "sbt & Paradox (JDK 8)"
      script: sbt test docs/paradox
      env: ADOPTOPENJDK=8

    - name: "sbt & Paradox (JDK 11)"
      script: sbt test docs/paradox
      env: ADOPTOPENJDK=11

    - name: "Maven (JDK 8)"
      ## set name to "hello-world-grpc" and accept all other defaults (--force)
      script: sbt new file://$PWD --name=hello-world-grpc --force && pushd hello-world-grpc &&  mvn test         && popd || travis_terminate 1
      env: ADOPTOPENJDK=8

    - name: "Maven (JDK 11)"
      ## set name to "hello-world-grpc" and accept all other defaults (--force)
      script: sbt new file://$PWD --name=hello-world-grpc --force && pushd hello-world-grpc &&  mvn test         && popd || travis_terminate 1
      env: ADOPTOPENJDK=11

    - name: "Gradle (JDK 8)"
      script: sbt new file://$PWD --name=hello-world-grpc --force && pushd hello-world-grpc &&  ./gradlew --console=plain build
      env: ADOPTOPENJDK=8

    - name: "Gradle (JDK 11)"
      script: sbt new file://$PWD --name=hello-world-grpc --force && pushd hello-world-grpc &&  ./gradlew --console=plain build
      env: ADOPTOPENJDK=11

stages:
  - name: check

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository

notifications:
  email:
    recipients:
      - akka.official@gmail.com
    on_success: never
    on_failure: always
    if: branch = master
