language: scala
scala:
  - 2.12.11

env:
  matrix:
    - TRAVIS_JDK=adopt@1.8.0-242
    - TRAVIS_JDK=adopt@1.11.0-6

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "$TRAVIS_JDK" && jabba use "$_" && java -Xmx32m -version

script:
 - sbt test docs/paradox

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.jabba/jdk
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.gradle
