name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */7 * *"

jobs:
  check:
    name: Build and test
    if: github.repository == 'akka/akka-grpc-quickstart-scala.g8'
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: coursier/setup-action@v1.3.0
        with:
          jvm: temurin:1.17

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: sbt & Paradox
        run: sbt test docs/paradox

      - name: sbt Scala 3
        run: |-
	  sbt new file://$PWD --name=hello-world --scala_version=3.3.1 --force && pushd hello-world &&  sbt test

      - name: Maven
        run: |-
          sbt new file://$PWD --name=hello-world-grpc --force && pushd hello-world-grpc &&  mvn test

      - name: Gradle
        run: |-
          sbt new file://$PWD --name=hello-world-grpc --force && pushd hello-world-grpc &&  ./gradlew --console=plain build -i --no-daemon

      - name: Email on failure
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Failed: ${{ github.workflow }} / ${{ github.job }}"
          to: akka.official@gmail.com
          from: Akka CI (GHActions)
          body: |
            Job ${{ github.job }} in workflow ${{ github.workflow }} of ${{github.repository}} failed!
            https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
